# CNN

In [2]:
import numpy as np

In [42]:
a=np.random.rand(2,2,2,3)*10
a

array([[[[9.92274762, 9.37761308, 4.61968156],
         [3.28609844, 3.941887  , 9.36847596]],

        [[0.06929576, 2.90682726, 7.53510333],
         [9.67059513, 0.50801208, 4.14999891]]],


       [[[1.51964033, 6.70496876, 8.64986705],
         [6.84262684, 1.43865777, 5.94775237]],

        [[6.5569591 , 8.64440001, 7.11173515],
         [9.17445787, 1.38531977, 0.761623  ]]]])

In [53]:
b= np.pad(a, ((0,0),(1,1), (1,1),(0,0)), 'constant', constant_values = (0,0))
b

array([[[[0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ]],

        [[0.        , 0.        , 0.        ],
         [9.92274762, 9.37761308, 4.61968156],
         [3.28609844, 3.941887  , 9.36847596],
         [0.        , 0.        , 0.        ]],

        [[0.        , 0.        , 0.        ],
         [0.06929576, 2.90682726, 7.53510333],
         [9.67059513, 0.50801208, 4.14999891],
         [0.        , 0.        , 0.        ]],

        [[0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ]]],


       [[[0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ]],

        [[0.        , 0.        , 0.        ],
 

In [59]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c[0:2,0:2]

array([[1, 2],
       [4, 5]])